### ISSUE TITLE
Where is `stackbit dev` command?

### ISSUE THREAD

**Issue by VitaliyPotapov** [stackbit/stackbit-cli#4]
In [documentation](https://docs.stackbit.com/reference/stackbit-cli#dev) there is a `stackbit dev` command, but it's missing in this repo.

**Comment by smnh** [comment]
Hi @VitaliyPotapov,
The stackbit-cli and stackbit-dev were moved to a different private repository.
We are planning to open this repository to the public soon. 
You can find the link to that repo on the npmjs page - https://www.npmjs.com/package/@stackbit/cli (it will take you to 404 page until we open it for a public access).

By the way, if you want to checkout the code of stackbit-dev without waiting for us to open that repo, you can npm install `@stackbit/cli`, and navigate to `node_modules/@stackbit/dev` to see the code. We publish the packages with full source code in the `src` folder.

**Comment by VitaliyPotapov** [comment]
Thanks @smnh ! I will check.

Btw maybe you have a suggestion for my original task: 
We need to run stackbit on a custom branches to be able to test pull-requests before merge. My current idea is to run `stackbit dev` on vercel and share link to testers. Do you think it's possible? Maybe there is another approach?

**Comment by youvalv** [comment]
Hi @VitaliyPotapov!

Can you share some more details on the workflow? 
what testers are expecting? a "live site" deployed from a specific branch?

**Comment by youvalv** [comment]
@VitaliyPotapov better to email us at support@stackbit.com so we can continue there and close this issue

**Comment by VitaliyPotapov** [comment]
> @VitaliyPotapov better to email us at [support@stackbit.com](mailto:support@stackbit.com) so we can continue there and close this issue

Okey, thanks!
